version: "3.8"
services:
  postgres:
    image: postgres:15-alpine
    container_name: my_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tasks
      POSTGRES_PASSWORD: tasks
      POSTGRES_DB: dbname
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tasks -d dbname"]
      interval: 5s
      timeout: 5s
      retries: 5
  todolist:
    build: .
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - TODO_PORT=3000
      - TODO_DBUSER=tasks
      - TODO_DBPASS=tasks
      - TODO_DBHOST=postgres
      - TODO_DBPORT=5432
      - TODO_DBNAME=dbname
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  pgdata: