version: "3.8"
services:
  postgres:
    image: postgres:15-alpine
    container_name: my_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tasks
      POSTGRES_PASSWORD: tasks
      POSTGRES_DB: dbname
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: